### ISSUE TITLE
Add documentation for installing in local machine

### ISSUE THREAD

**Issue by malay5** [AzeemIdrisi/InstaLoaderApp#3]
The documentation lacks in providing information on how to install it in local machine

**Comment by AzeemIdrisi** [comment]
Simply open the project in Android Studio, It uses Chaquopy Python SDK, You might need to configure the python executable path for your machine.

**Comment by malay5** [comment]
I meant, adding it in readme.md

**Comment by AzeemIdrisi** [comment]
The README.md is about the usage of the app and not meant to describe the development setup. It's pretty simple anyways.
