### ISSUE TITLE
Option to download single post using post link

### ISSUE THREAD

**Issue by AzeemIdrisi** [AzeemIdrisi/InstaLoaderApp#8]
There must be an option to download a single post by pasting the URL of the post.

It would be great if the user had the choice of selecting a particular or a number of media when there were multiple media present in the post.

**Comment by PuruSinghvi** [comment]
hey, I would like to add this feature into the app, can you please assign this to me?
Thank you

**Comment by AzeemIdrisi** [comment]
Assigned to you. Good luck.
